name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./blog-copy

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: ./blog-copy/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Build
        # baseHref уже в angular.json, но можно продублировать для надёжности
        run: npx ng build --configuration production

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./blog-copy/dist/blog-copy/browser
